language: php

os:
    - linux

php:
    # one version fo Behat is enought
    - '7.4'

services:
    - mysql
    - xvfb

env:
  global:
    - SELENIUM_MAJ_VER=3.141
    - SELENIUM_VER=${SELENIUM_MAJ_VER}.59
    - SELENIUM_JAR=selenium-server-standalone-${SELENIUM_VER}.jar
    - CHROME_DRIVER_VER=2.44

addons:
  apt:
    update: true
    chrome: stable
  hosts:
    - mysql

install:
  - Xvfb :99 -screen 0 1280x1024x16 +extension RANDR > /dev/null 2>&1 &

before_install:
    - npm get prefix
    - npm install -g less less-plugin-clean-css uglify-js

before_script:
    # Setup selenium
    - wget --no-verbose https://selenium-release.storage.googleapis.com/${SELENIUM_MAJ_VER}/${SELENIUM_JAR}
    - java -jar ${SELENIUM_JAR} > /dev/null 2>&1 &

    # Setup chromedriver
    - wget --no-verbose http://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VER}/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    #- "wget --no-verbose http://selenium-release.storage.googleapis.com/3.0-beta3/selenium-server-standalone-3.0.0-beta3.jar -O selenium-server-standalone.jar && sudo mv selenium-server-standalone.jar /usr/local/bin"
    #- "wget --no-verbose http://chromedriver.storage.googleapis.com/2.23/chromedriver_linux64.zip -O chromedriver.zip && unzip chromedriver.zip && sudo mv chromedriver /usr/local/bin"
    #- "java  -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver  -jar /usr/local/bin/selenium-server-standalone.jar &"
    #- sleep 3
    #- sudo whereis google-chrome

    - php -S localhost:8888 > /dev/null 2>&1&

    - mysql -e "CREATE DATABASE atk4_test__ui;"
    - mysql -e "CREATE USER 'atk4_test'@'127.0.0.1' IDENTIFIED BY 'atk4_pass';"
    - mysql -e "GRANT ALL ON atk4_test__ui.* TO 'atk4_test'@'127.0.0.1';"
    - mysql -uatk4_test -patk4_pass -h mysql atk4_test__ui < demos/atk4.sql
    - cp demos/db.example.php demos/db.php

    - (cd js; npm install --loglevel=error; npm run build)
    - lessc public/agileui.less public/agileui.css --clean-css="--s1 --advanced" --source-map
    - uglifyjs --compress -- public/agileui.js > public/agileui.min.js
    - composer install --no-suggest --ansi --prefer-dist --no-interaction --no-progress --optimize-autoloader

script:
    #- mkdir -p coverage
    #- chmod 777 coverage
    #- cp tools/coverage.php demos/coverage.php
    - vendor/bin/behat --config behat-travis.yml || exit -1
    #- killall -s SIGINT --wait php # flush coverage files for Behat
    #- ls -l coverage/ | wc -l
    #- vendor/bin/phpcov  merge coverage/ --clover clover.xml

cache:
  directories:
    - $HOME/.composer/cache
