name: Unit Testing

on:
  pull_request:
    branches: '**'
  push:
    branches: '**'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  unit-test:
    name: Unit
    runs-on: ubuntu-latest
    container:
      image: atk4/image:${{ matrix.php }} # https://github.com/atk4/image
    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', 'latest']
        type: ['Phpunit']
        include:
          - php: 'latest'
            type: 'Behat'
          - php: 'latest'
            type: 'CodingStyle'
    env:
      LOG_COVERAGE: "${{ fromJSON('{true: \"1\", false: \"\"}')[matrix.php == 'latest' && matrix.type == 'Phpunit' && (github.event_name == 'pull_request' || (github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')))] }}"
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: atk4_pass
          MYSQL_USER: atk4_test
          MYSQL_PASSWORD: atk4_pass
          MYSQL_DATABASE: atk4_test__ui
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure PHP
        run: |
          if [ -z "$LOG_COVERAGE" ]; then rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ; fi
          php --version

      - name: Setup cache 1/2
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup cache 2/2
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ matrix.type }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: |
          if [ "${{ matrix.type }}" != "Phpunit" ]; then composer remove --no-interaction --no-update phpunit/phpunit phpunit/phpcov --dev ; fi
          if [ "${{ matrix.type }}" != "Behat" ]; then composer remove --no-interaction --no-update 'behat/*' --dev ; fi
          if [ "${{ matrix.type }}" != "CodingStyle" ]; then composer remove --no-interaction --no-update friendsofphp/php-cs-fixer --dev ; fi
          composer install --no-suggest --ansi --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Install JS dependencies (only for Behat)
        if: matrix.type == 'Behat'
        run: |
          apk add npm
          npm install --loglevel=error -g less less-plugin-clean-css uglify-js
          (cd js && npm install --loglevel=error)

      - name: Build JS files (only for Behat)
        if: matrix.type == 'Behat'
        run: |
          # atk js
          (cd js && npm run build)

          # release command:
          # lessc public/agileui.less public/agileui.css --clean-css="--s1 --advanced" --source-map
          lessc public/agileui.less public/agileui.css

          # app js
          # ignored from git - check syntax only
          uglifyjs --compress -- public/agileui.js > public/agileui.min.js

      - name: Init
        run: |
          mkdir -p build/logs
          mysql -uatk4_test -patk4_pass -h mysql atk4_test__ui < demos/atk4.sql
          cp demos/db.example.php demos/db.php

      - name: "Run tests: Phpunit (only for Phpunit)"
        if: matrix.type == 'Phpunit'
        run: |
          if [ -n "$LOG_COVERAGE" ]; then
            vendor/bin/phpunit --coverage-text -v
            ls -l coverage | wc -l && mv coverage/* build/logs
          else
            vendor/bin/phpunit --no-coverage -v
          fi

#      - name: "Run tests: Behat (only for Behat)"
#        if: matrix.type == 'Behat'
#        run: TODO migrate from Travis CI

      - name: Lint / check syntax (only for CodingStyle)
        if: matrix.type == 'CodingStyle'
        run: find . \( -type d \( -path './vendor/*' \) \) -prune -o ! -type d -name '*.php' -print0 | xargs -0 -n1 php -l

      - name: Check Coding Style (only for CodingStyle)
        if: matrix.type == 'CodingStyle'
        run: vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --diff --diff-format=udiff --verbose --show-progress=dots

      - name: Upload coverage logs 1/2 (only for "latest" Phpunit)
        if: env.LOG_COVERAGE
        run: vendor/bin/phpcov merge build/logs/ --clover build/logs/cc.xml

      - name: Upload coverage logs 2/2 (only for "latest" Phpunit)
        if: env.LOG_COVERAGE
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/logs/cc.xml
